# Some useful links for new staff members

## Links to get your digital profile up and running

### Useful staff info management sites

1. [Explanation page](https://www.en.its.aau.dk/instructions/staff-profile) - this site provides a brief description of the two links that are replicated below

    a. [PURE / VBN](https://vbn.aau.dk/admin/workspace/personal/overview/) - for managing the research related content on your VBN profile. Activities, media presence, project participation and the connections that these all have to the various networks in AAU.

    b. [PDS](https://www.its.aau.dk/vejledninger/medarbejderprofil) - This page allows you to upload a new profile image, change your nickname, check your holidays and your core personal data. The research and teaching info on this page are, however, superceded by the info you enter on the PURE platform - So don't bother editing it here.
    
2. [Plan2Learn](https://aau.plan2learn.dk/default.aspx?lang=en) - This is where 
you will find information on the courses available for staff development. For 
example there are first aid courses in both Danish and English that you could
sign up for there.

3. [Insight - Teaching hours system](https://apps.powerapps.com/play/6050b6e6-8414-4bef-8f28-6f41944878cd?tenantId=f5dbba49-ce06-496f-ac3e-0cf14361d934&source=email&hint=08e5ae4b-a9f2-41c1-9774-945ccbf54ae4)


## Useful generic shortcuts

1. [AAU University library](http://www.aub.aau.dk/)

2. [AAU Mail server](mail.aau.dk)

3. [AAU Moodle dashboard page](https://www.moodle.aau.dk/my/)

4. [AAU design guide, templates and logos](https://www.design.aau.dk) - unfortunately only in Danish

5. [AAU Business School presentation and design templates](https://www.intranet.business.aau.dk/business-school-design-materials)

6. [AAU Business School homepage](https://www.business.aau.dk)

6. [List of printers and setup guides](https://www.its.aau.dk/vejledninger/Printkopi/find-printere/)

7. [The IT purchase catalogue](https://www.en.ekstranet.its.aau.dk/purchase)


## Links to university support systems

1. [CALDISS](https://www.en.caldiss.aau.dk) - For training in data analytics software, access to amazing data and general digital guidance.

2. [CLAUDIA](https://www.claaudia.aau.dk) - For assistance with Research data and IT hardware services.

3. [AI for the people](https://www.ai.aau.dk) - For help implementing AI based technologies in your research or projects.


## A supervision materials page

[This is just a GitPage dump of communication and tools that have I have used in supervision.](https://robabsmith.github.io/supervision_gitpage/) All of the content is generated by RMarkdown - as is this site - and all of the back end code is available in the Git repository (`main` branch) behind the page (`gh-pages` branch).